spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:tech;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
